# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1023cdac01b8aacc4cf4f5e92ac92b9b97648507b6fd20681b8ab32d2194c6f5b5e38c272815792e50cd83680adf180f7762e10a982447f5166ac6297a204d33

test:
  secret_key_base: b385f11404e596fb43dca335ea7548ce2ff1b325e00bbc376f82d927452ece4ab1360a591852ad63dd4fa6d8c845096df738747f1e7c636c22be217447c1fd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
